// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nullsploit01/iosync/ent/node"
	"github.com/nullsploit01/iosync/ent/nodeapikey"
	"github.com/nullsploit01/iosync/ent/predicate"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (nu *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetName sets the "name" field.
func (nu *NodeUpdate) SetName(s string) *NodeUpdate {
	nu.mutation.SetName(s)
	return nu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableName(s *string) *NodeUpdate {
	if s != nil {
		nu.SetName(*s)
	}
	return nu
}

// SetDescription sets the "description" field.
func (nu *NodeUpdate) SetDescription(s string) *NodeUpdate {
	nu.mutation.SetDescription(s)
	return nu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableDescription(s *string) *NodeUpdate {
	if s != nil {
		nu.SetDescription(*s)
	}
	return nu
}

// SetIsActive sets the "is_active" field.
func (nu *NodeUpdate) SetIsActive(b bool) *NodeUpdate {
	nu.mutation.SetIsActive(b)
	return nu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableIsActive(b *bool) *NodeUpdate {
	if b != nil {
		nu.SetIsActive(*b)
	}
	return nu
}

// SetIsOnline sets the "is_online" field.
func (nu *NodeUpdate) SetIsOnline(b bool) *NodeUpdate {
	nu.mutation.SetIsOnline(b)
	return nu
}

// SetNillableIsOnline sets the "is_online" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableIsOnline(b *bool) *NodeUpdate {
	if b != nil {
		nu.SetIsOnline(*b)
	}
	return nu
}

// SetLastOnlineAt sets the "last_online_at" field.
func (nu *NodeUpdate) SetLastOnlineAt(t time.Time) *NodeUpdate {
	nu.mutation.SetLastOnlineAt(t)
	return nu
}

// SetNillableLastOnlineAt sets the "last_online_at" field if the given value is not nil.
func (nu *NodeUpdate) SetNillableLastOnlineAt(t *time.Time) *NodeUpdate {
	if t != nil {
		nu.SetLastOnlineAt(*t)
	}
	return nu
}

// ClearLastOnlineAt clears the value of the "last_online_at" field.
func (nu *NodeUpdate) ClearLastOnlineAt() *NodeUpdate {
	nu.mutation.ClearLastOnlineAt()
	return nu
}

// SetUpdatedAt sets the "updated_at" field.
func (nu *NodeUpdate) SetUpdatedAt(t time.Time) *NodeUpdate {
	nu.mutation.SetUpdatedAt(t)
	return nu
}

// AddAPIKeyIDs adds the "api_keys" edge to the NodeApiKey entity by IDs.
func (nu *NodeUpdate) AddAPIKeyIDs(ids ...int) *NodeUpdate {
	nu.mutation.AddAPIKeyIDs(ids...)
	return nu
}

// AddAPIKeys adds the "api_keys" edges to the NodeApiKey entity.
func (nu *NodeUpdate) AddAPIKeys(n ...*NodeApiKey) *NodeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.AddAPIKeyIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nu *NodeUpdate) Mutation() *NodeMutation {
	return nu.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the NodeApiKey entity.
func (nu *NodeUpdate) ClearAPIKeys() *NodeUpdate {
	nu.mutation.ClearAPIKeys()
	return nu
}

// RemoveAPIKeyIDs removes the "api_keys" edge to NodeApiKey entities by IDs.
func (nu *NodeUpdate) RemoveAPIKeyIDs(ids ...int) *NodeUpdate {
	nu.mutation.RemoveAPIKeyIDs(ids...)
	return nu
}

// RemoveAPIKeys removes "api_keys" edges to NodeApiKey entities.
func (nu *NodeUpdate) RemoveAPIKeys(n ...*NodeApiKey) *NodeUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nu.RemoveAPIKeyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NodeUpdate) Save(ctx context.Context) (int, error) {
	nu.defaults()
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NodeUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NodeUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NodeUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

func (nu *NodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := nu.mutation.Description(); ok {
		_spec.SetField(node.FieldDescription, field.TypeString, value)
	}
	if value, ok := nu.mutation.IsActive(); ok {
		_spec.SetField(node.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := nu.mutation.IsOnline(); ok {
		_spec.SetField(node.FieldIsOnline, field.TypeBool, value)
	}
	if value, ok := nu.mutation.LastOnlineAt(); ok {
		_spec.SetField(node.FieldLastOnlineAt, field.TypeTime, value)
	}
	if nu.mutation.LastOnlineAtCleared() {
		_spec.ClearField(node.FieldLastOnlineAt, field.TypeTime)
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if nu.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.APIKeysTable,
			Columns: []string{node.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeapikey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !nu.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.APIKeysTable,
			Columns: []string{node.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeapikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.APIKeysTable,
			Columns: []string{node.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeapikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetName sets the "name" field.
func (nuo *NodeUpdateOne) SetName(s string) *NodeUpdateOne {
	nuo.mutation.SetName(s)
	return nuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableName(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetName(*s)
	}
	return nuo
}

// SetDescription sets the "description" field.
func (nuo *NodeUpdateOne) SetDescription(s string) *NodeUpdateOne {
	nuo.mutation.SetDescription(s)
	return nuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableDescription(s *string) *NodeUpdateOne {
	if s != nil {
		nuo.SetDescription(*s)
	}
	return nuo
}

// SetIsActive sets the "is_active" field.
func (nuo *NodeUpdateOne) SetIsActive(b bool) *NodeUpdateOne {
	nuo.mutation.SetIsActive(b)
	return nuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableIsActive(b *bool) *NodeUpdateOne {
	if b != nil {
		nuo.SetIsActive(*b)
	}
	return nuo
}

// SetIsOnline sets the "is_online" field.
func (nuo *NodeUpdateOne) SetIsOnline(b bool) *NodeUpdateOne {
	nuo.mutation.SetIsOnline(b)
	return nuo
}

// SetNillableIsOnline sets the "is_online" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableIsOnline(b *bool) *NodeUpdateOne {
	if b != nil {
		nuo.SetIsOnline(*b)
	}
	return nuo
}

// SetLastOnlineAt sets the "last_online_at" field.
func (nuo *NodeUpdateOne) SetLastOnlineAt(t time.Time) *NodeUpdateOne {
	nuo.mutation.SetLastOnlineAt(t)
	return nuo
}

// SetNillableLastOnlineAt sets the "last_online_at" field if the given value is not nil.
func (nuo *NodeUpdateOne) SetNillableLastOnlineAt(t *time.Time) *NodeUpdateOne {
	if t != nil {
		nuo.SetLastOnlineAt(*t)
	}
	return nuo
}

// ClearLastOnlineAt clears the value of the "last_online_at" field.
func (nuo *NodeUpdateOne) ClearLastOnlineAt() *NodeUpdateOne {
	nuo.mutation.ClearLastOnlineAt()
	return nuo
}

// SetUpdatedAt sets the "updated_at" field.
func (nuo *NodeUpdateOne) SetUpdatedAt(t time.Time) *NodeUpdateOne {
	nuo.mutation.SetUpdatedAt(t)
	return nuo
}

// AddAPIKeyIDs adds the "api_keys" edge to the NodeApiKey entity by IDs.
func (nuo *NodeUpdateOne) AddAPIKeyIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.AddAPIKeyIDs(ids...)
	return nuo
}

// AddAPIKeys adds the "api_keys" edges to the NodeApiKey entity.
func (nuo *NodeUpdateOne) AddAPIKeys(n ...*NodeApiKey) *NodeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.AddAPIKeyIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (nuo *NodeUpdateOne) Mutation() *NodeMutation {
	return nuo.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the NodeApiKey entity.
func (nuo *NodeUpdateOne) ClearAPIKeys() *NodeUpdateOne {
	nuo.mutation.ClearAPIKeys()
	return nuo
}

// RemoveAPIKeyIDs removes the "api_keys" edge to NodeApiKey entities by IDs.
func (nuo *NodeUpdateOne) RemoveAPIKeyIDs(ids ...int) *NodeUpdateOne {
	nuo.mutation.RemoveAPIKeyIDs(ids...)
	return nuo
}

// RemoveAPIKeys removes "api_keys" edges to NodeApiKey entities.
func (nuo *NodeUpdateOne) RemoveAPIKeys(n ...*NodeApiKey) *NodeUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nuo.RemoveAPIKeyIDs(ids...)
}

// Where appends a list predicates to the NodeUpdate builder.
func (nuo *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Node entity.
func (nuo *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	nuo.defaults()
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NodeUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

func (nuo *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Name(); ok {
		_spec.SetField(node.FieldName, field.TypeString, value)
	}
	if value, ok := nuo.mutation.Description(); ok {
		_spec.SetField(node.FieldDescription, field.TypeString, value)
	}
	if value, ok := nuo.mutation.IsActive(); ok {
		_spec.SetField(node.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := nuo.mutation.IsOnline(); ok {
		_spec.SetField(node.FieldIsOnline, field.TypeBool, value)
	}
	if value, ok := nuo.mutation.LastOnlineAt(); ok {
		_spec.SetField(node.FieldLastOnlineAt, field.TypeTime, value)
	}
	if nuo.mutation.LastOnlineAtCleared() {
		_spec.ClearField(node.FieldLastOnlineAt, field.TypeTime)
	}
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if nuo.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.APIKeysTable,
			Columns: []string{node.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeapikey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !nuo.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.APIKeysTable,
			Columns: []string{node.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeapikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   node.APIKeysTable,
			Columns: []string{node.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nodeapikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Node{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
