services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iosync
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - iosync-volume:/var/lib/postgresql/data/

  mosquitto:
    image: "eclipse-mosquitto"
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  iosync-volume:
  mosquitto:
