// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"iosync/ent/apikey"
	"iosync/ent/device"
	"iosync/ent/topic"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApiKeyCreate is the builder for creating a ApiKey entity.
type ApiKeyCreate struct {
	config
	mutation *ApiKeyMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (akc *ApiKeyCreate) SetKey(s string) *ApiKeyCreate {
	akc.mutation.SetKey(s)
	return akc
}

// SetIsActive sets the "is_active" field.
func (akc *ApiKeyCreate) SetIsActive(b bool) *ApiKeyCreate {
	akc.mutation.SetIsActive(b)
	return akc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableIsActive(b *bool) *ApiKeyCreate {
	if b != nil {
		akc.SetIsActive(*b)
	}
	return akc
}

// SetRevokedAt sets the "revoked_at" field.
func (akc *ApiKeyCreate) SetRevokedAt(t time.Time) *ApiKeyCreate {
	akc.mutation.SetRevokedAt(t)
	return akc
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableRevokedAt(t *time.Time) *ApiKeyCreate {
	if t != nil {
		akc.SetRevokedAt(*t)
	}
	return akc
}

// SetLastUsed sets the "last_used" field.
func (akc *ApiKeyCreate) SetLastUsed(t time.Time) *ApiKeyCreate {
	akc.mutation.SetLastUsed(t)
	return akc
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableLastUsed(t *time.Time) *ApiKeyCreate {
	if t != nil {
		akc.SetLastUsed(*t)
	}
	return akc
}

// SetCreatedAt sets the "created_at" field.
func (akc *ApiKeyCreate) SetCreatedAt(t time.Time) *ApiKeyCreate {
	akc.mutation.SetCreatedAt(t)
	return akc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableCreatedAt(t *time.Time) *ApiKeyCreate {
	if t != nil {
		akc.SetCreatedAt(*t)
	}
	return akc
}

// SetUpdatedAt sets the "updated_at" field.
func (akc *ApiKeyCreate) SetUpdatedAt(t time.Time) *ApiKeyCreate {
	akc.mutation.SetUpdatedAt(t)
	return akc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableUpdatedAt(t *time.Time) *ApiKeyCreate {
	if t != nil {
		akc.SetUpdatedAt(*t)
	}
	return akc
}

// SetExpiresAt sets the "expires_at" field.
func (akc *ApiKeyCreate) SetExpiresAt(t time.Time) *ApiKeyCreate {
	akc.mutation.SetExpiresAt(t)
	return akc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableExpiresAt(t *time.Time) *ApiKeyCreate {
	if t != nil {
		akc.SetExpiresAt(*t)
	}
	return akc
}

// SetDescription sets the "description" field.
func (akc *ApiKeyCreate) SetDescription(s string) *ApiKeyCreate {
	akc.mutation.SetDescription(s)
	return akc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableDescription(s *string) *ApiKeyCreate {
	if s != nil {
		akc.SetDescription(*s)
	}
	return akc
}

// SetDeviceID sets the "device" edge to the Device entity by ID.
func (akc *ApiKeyCreate) SetDeviceID(id int) *ApiKeyCreate {
	akc.mutation.SetDeviceID(id)
	return akc
}

// SetNillableDeviceID sets the "device" edge to the Device entity by ID if the given value is not nil.
func (akc *ApiKeyCreate) SetNillableDeviceID(id *int) *ApiKeyCreate {
	if id != nil {
		akc = akc.SetDeviceID(*id)
	}
	return akc
}

// SetDevice sets the "device" edge to the Device entity.
func (akc *ApiKeyCreate) SetDevice(d *Device) *ApiKeyCreate {
	return akc.SetDeviceID(d.ID)
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (akc *ApiKeyCreate) AddTopicIDs(ids ...int) *ApiKeyCreate {
	akc.mutation.AddTopicIDs(ids...)
	return akc
}

// AddTopics adds the "topics" edges to the Topic entity.
func (akc *ApiKeyCreate) AddTopics(t ...*Topic) *ApiKeyCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return akc.AddTopicIDs(ids...)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (akc *ApiKeyCreate) Mutation() *ApiKeyMutation {
	return akc.mutation
}

// Save creates the ApiKey in the database.
func (akc *ApiKeyCreate) Save(ctx context.Context) (*ApiKey, error) {
	akc.defaults()
	return withHooks(ctx, akc.sqlSave, akc.mutation, akc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (akc *ApiKeyCreate) SaveX(ctx context.Context) *ApiKey {
	v, err := akc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (akc *ApiKeyCreate) Exec(ctx context.Context) error {
	_, err := akc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akc *ApiKeyCreate) ExecX(ctx context.Context) {
	if err := akc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (akc *ApiKeyCreate) defaults() {
	if _, ok := akc.mutation.IsActive(); !ok {
		v := apikey.DefaultIsActive
		akc.mutation.SetIsActive(v)
	}
	if _, ok := akc.mutation.LastUsed(); !ok {
		v := apikey.DefaultLastUsed()
		akc.mutation.SetLastUsed(v)
	}
	if _, ok := akc.mutation.CreatedAt(); !ok {
		v := apikey.DefaultCreatedAt()
		akc.mutation.SetCreatedAt(v)
	}
	if _, ok := akc.mutation.UpdatedAt(); !ok {
		v := apikey.DefaultUpdatedAt()
		akc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (akc *ApiKeyCreate) check() error {
	if _, ok := akc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "ApiKey.key"`)}
	}
	if _, ok := akc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ApiKey.is_active"`)}
	}
	if _, ok := akc.mutation.LastUsed(); !ok {
		return &ValidationError{Name: "last_used", err: errors.New(`ent: missing required field "ApiKey.last_used"`)}
	}
	if _, ok := akc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ApiKey.created_at"`)}
	}
	if _, ok := akc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ApiKey.updated_at"`)}
	}
	return nil
}

func (akc *ApiKeyCreate) sqlSave(ctx context.Context) (*ApiKey, error) {
	if err := akc.check(); err != nil {
		return nil, err
	}
	_node, _spec := akc.createSpec()
	if err := sqlgraph.CreateNode(ctx, akc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	akc.mutation.id = &_node.ID
	akc.mutation.done = true
	return _node, nil
}

func (akc *ApiKeyCreate) createSpec() (*ApiKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ApiKey{config: akc.config}
		_spec = sqlgraph.NewCreateSpec(apikey.Table, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt))
	)
	if value, ok := akc.mutation.Key(); ok {
		_spec.SetField(apikey.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := akc.mutation.IsActive(); ok {
		_spec.SetField(apikey.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := akc.mutation.RevokedAt(); ok {
		_spec.SetField(apikey.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := akc.mutation.LastUsed(); ok {
		_spec.SetField(apikey.FieldLastUsed, field.TypeTime, value)
		_node.LastUsed = value
	}
	if value, ok := akc.mutation.CreatedAt(); ok {
		_spec.SetField(apikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := akc.mutation.UpdatedAt(); ok {
		_spec.SetField(apikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := akc.mutation.ExpiresAt(); ok {
		_spec.SetField(apikey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := akc.mutation.Description(); ok {
		_spec.SetField(apikey.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if nodes := akc.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   apikey.DeviceTable,
			Columns: []string{apikey.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.device_api_key = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := akc.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.TopicsTable,
			Columns: []string{apikey.TopicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ApiKeyCreateBulk is the builder for creating many ApiKey entities in bulk.
type ApiKeyCreateBulk struct {
	config
	err      error
	builders []*ApiKeyCreate
}

// Save creates the ApiKey entities in the database.
func (akcb *ApiKeyCreateBulk) Save(ctx context.Context) ([]*ApiKey, error) {
	if akcb.err != nil {
		return nil, akcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(akcb.builders))
	nodes := make([]*ApiKey, len(akcb.builders))
	mutators := make([]Mutator, len(akcb.builders))
	for i := range akcb.builders {
		func(i int, root context.Context) {
			builder := akcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApiKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, akcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, akcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, akcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (akcb *ApiKeyCreateBulk) SaveX(ctx context.Context) []*ApiKey {
	v, err := akcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (akcb *ApiKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := akcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akcb *ApiKeyCreateBulk) ExecX(ctx context.Context) {
	if err := akcb.Exec(ctx); err != nil {
		panic(err)
	}
}
