// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"iosync/ent/apikeys"
	"iosync/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApiKeysQuery is the builder for querying ApiKeys entities.
type ApiKeysQuery struct {
	config
	ctx        *QueryContext
	order      []apikeys.OrderOption
	inters     []Interceptor
	predicates []predicate.ApiKeys
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApiKeysQuery builder.
func (akq *ApiKeysQuery) Where(ps ...predicate.ApiKeys) *ApiKeysQuery {
	akq.predicates = append(akq.predicates, ps...)
	return akq
}

// Limit the number of records to be returned by this query.
func (akq *ApiKeysQuery) Limit(limit int) *ApiKeysQuery {
	akq.ctx.Limit = &limit
	return akq
}

// Offset to start from.
func (akq *ApiKeysQuery) Offset(offset int) *ApiKeysQuery {
	akq.ctx.Offset = &offset
	return akq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (akq *ApiKeysQuery) Unique(unique bool) *ApiKeysQuery {
	akq.ctx.Unique = &unique
	return akq
}

// Order specifies how the records should be ordered.
func (akq *ApiKeysQuery) Order(o ...apikeys.OrderOption) *ApiKeysQuery {
	akq.order = append(akq.order, o...)
	return akq
}

// First returns the first ApiKeys entity from the query.
// Returns a *NotFoundError when no ApiKeys was found.
func (akq *ApiKeysQuery) First(ctx context.Context) (*ApiKeys, error) {
	nodes, err := akq.Limit(1).All(setContextOp(ctx, akq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apikeys.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (akq *ApiKeysQuery) FirstX(ctx context.Context) *ApiKeys {
	node, err := akq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApiKeys ID from the query.
// Returns a *NotFoundError when no ApiKeys ID was found.
func (akq *ApiKeysQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(1).IDs(setContextOp(ctx, akq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apikeys.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (akq *ApiKeysQuery) FirstIDX(ctx context.Context) int {
	id, err := akq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApiKeys entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApiKeys entity is found.
// Returns a *NotFoundError when no ApiKeys entities are found.
func (akq *ApiKeysQuery) Only(ctx context.Context) (*ApiKeys, error) {
	nodes, err := akq.Limit(2).All(setContextOp(ctx, akq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apikeys.Label}
	default:
		return nil, &NotSingularError{apikeys.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (akq *ApiKeysQuery) OnlyX(ctx context.Context) *ApiKeys {
	node, err := akq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApiKeys ID in the query.
// Returns a *NotSingularError when more than one ApiKeys ID is found.
// Returns a *NotFoundError when no entities are found.
func (akq *ApiKeysQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(2).IDs(setContextOp(ctx, akq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apikeys.Label}
	default:
		err = &NotSingularError{apikeys.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (akq *ApiKeysQuery) OnlyIDX(ctx context.Context) int {
	id, err := akq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApiKeysSlice.
func (akq *ApiKeysQuery) All(ctx context.Context) ([]*ApiKeys, error) {
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryAll)
	if err := akq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApiKeys, *ApiKeysQuery]()
	return withInterceptors[[]*ApiKeys](ctx, akq, qr, akq.inters)
}

// AllX is like All, but panics if an error occurs.
func (akq *ApiKeysQuery) AllX(ctx context.Context) []*ApiKeys {
	nodes, err := akq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApiKeys IDs.
func (akq *ApiKeysQuery) IDs(ctx context.Context) (ids []int, err error) {
	if akq.ctx.Unique == nil && akq.path != nil {
		akq.Unique(true)
	}
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryIDs)
	if err = akq.Select(apikeys.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (akq *ApiKeysQuery) IDsX(ctx context.Context) []int {
	ids, err := akq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (akq *ApiKeysQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryCount)
	if err := akq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, akq, querierCount[*ApiKeysQuery](), akq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (akq *ApiKeysQuery) CountX(ctx context.Context) int {
	count, err := akq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (akq *ApiKeysQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryExist)
	switch _, err := akq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (akq *ApiKeysQuery) ExistX(ctx context.Context) bool {
	exist, err := akq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApiKeysQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (akq *ApiKeysQuery) Clone() *ApiKeysQuery {
	if akq == nil {
		return nil
	}
	return &ApiKeysQuery{
		config:     akq.config,
		ctx:        akq.ctx.Clone(),
		order:      append([]apikeys.OrderOption{}, akq.order...),
		inters:     append([]Interceptor{}, akq.inters...),
		predicates: append([]predicate.ApiKeys{}, akq.predicates...),
		// clone intermediate query.
		sql:  akq.sql.Clone(),
		path: akq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApiKeys.Query().
//		GroupBy(apikeys.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (akq *ApiKeysQuery) GroupBy(field string, fields ...string) *ApiKeysGroupBy {
	akq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApiKeysGroupBy{build: akq}
	grbuild.flds = &akq.ctx.Fields
	grbuild.label = apikeys.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.ApiKeys.Query().
//		Select(apikeys.FieldKey).
//		Scan(ctx, &v)
func (akq *ApiKeysQuery) Select(fields ...string) *ApiKeysSelect {
	akq.ctx.Fields = append(akq.ctx.Fields, fields...)
	sbuild := &ApiKeysSelect{ApiKeysQuery: akq}
	sbuild.label = apikeys.Label
	sbuild.flds, sbuild.scan = &akq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApiKeysSelect configured with the given aggregations.
func (akq *ApiKeysQuery) Aggregate(fns ...AggregateFunc) *ApiKeysSelect {
	return akq.Select().Aggregate(fns...)
}

func (akq *ApiKeysQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range akq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, akq); err != nil {
				return err
			}
		}
	}
	for _, f := range akq.ctx.Fields {
		if !apikeys.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if akq.path != nil {
		prev, err := akq.path(ctx)
		if err != nil {
			return err
		}
		akq.sql = prev
	}
	return nil
}

func (akq *ApiKeysQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApiKeys, error) {
	var (
		nodes = []*ApiKeys{}
		_spec = akq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApiKeys).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApiKeys{config: akq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, akq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (akq *ApiKeysQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := akq.querySpec()
	_spec.Node.Columns = akq.ctx.Fields
	if len(akq.ctx.Fields) > 0 {
		_spec.Unique = akq.ctx.Unique != nil && *akq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, akq.driver, _spec)
}

func (akq *ApiKeysQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(apikeys.Table, apikeys.Columns, sqlgraph.NewFieldSpec(apikeys.FieldID, field.TypeInt))
	_spec.From = akq.sql
	if unique := akq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if akq.path != nil {
		_spec.Unique = true
	}
	if fields := akq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeys.FieldID)
		for i := range fields {
			if fields[i] != apikeys.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := akq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := akq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := akq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := akq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (akq *ApiKeysQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(akq.driver.Dialect())
	t1 := builder.Table(apikeys.Table)
	columns := akq.ctx.Fields
	if len(columns) == 0 {
		columns = apikeys.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if akq.sql != nil {
		selector = akq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if akq.ctx.Unique != nil && *akq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range akq.predicates {
		p(selector)
	}
	for _, p := range akq.order {
		p(selector)
	}
	if offset := akq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := akq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApiKeysGroupBy is the group-by builder for ApiKeys entities.
type ApiKeysGroupBy struct {
	selector
	build *ApiKeysQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (akgb *ApiKeysGroupBy) Aggregate(fns ...AggregateFunc) *ApiKeysGroupBy {
	akgb.fns = append(akgb.fns, fns...)
	return akgb
}

// Scan applies the selector query and scans the result into the given value.
func (akgb *ApiKeysGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, akgb.build.ctx, ent.OpQueryGroupBy)
	if err := akgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApiKeysQuery, *ApiKeysGroupBy](ctx, akgb.build, akgb, akgb.build.inters, v)
}

func (akgb *ApiKeysGroupBy) sqlScan(ctx context.Context, root *ApiKeysQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(akgb.fns))
	for _, fn := range akgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*akgb.flds)+len(akgb.fns))
		for _, f := range *akgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*akgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := akgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApiKeysSelect is the builder for selecting fields of ApiKeys entities.
type ApiKeysSelect struct {
	*ApiKeysQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aks *ApiKeysSelect) Aggregate(fns ...AggregateFunc) *ApiKeysSelect {
	aks.fns = append(aks.fns, fns...)
	return aks
}

// Scan applies the selector query and scans the result into the given value.
func (aks *ApiKeysSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aks.ctx, ent.OpQuerySelect)
	if err := aks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApiKeysQuery, *ApiKeysSelect](ctx, aks.ApiKeysQuery, aks, aks.inters, v)
}

func (aks *ApiKeysSelect) sqlScan(ctx context.Context, root *ApiKeysQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aks.fns))
	for _, fn := range aks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
