// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"iosync/ent/apikeys"
	"iosync/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApiKeysDelete is the builder for deleting a ApiKeys entity.
type ApiKeysDelete struct {
	config
	hooks    []Hook
	mutation *ApiKeysMutation
}

// Where appends a list predicates to the ApiKeysDelete builder.
func (akd *ApiKeysDelete) Where(ps ...predicate.ApiKeys) *ApiKeysDelete {
	akd.mutation.Where(ps...)
	return akd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (akd *ApiKeysDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, akd.sqlExec, akd.mutation, akd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (akd *ApiKeysDelete) ExecX(ctx context.Context) int {
	n, err := akd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (akd *ApiKeysDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apikeys.Table, sqlgraph.NewFieldSpec(apikeys.FieldID, field.TypeInt))
	if ps := akd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, akd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	akd.mutation.done = true
	return affected, err
}

// ApiKeysDeleteOne is the builder for deleting a single ApiKeys entity.
type ApiKeysDeleteOne struct {
	akd *ApiKeysDelete
}

// Where appends a list predicates to the ApiKeysDelete builder.
func (akdo *ApiKeysDeleteOne) Where(ps ...predicate.ApiKeys) *ApiKeysDeleteOne {
	akdo.akd.mutation.Where(ps...)
	return akdo
}

// Exec executes the deletion query.
func (akdo *ApiKeysDeleteOne) Exec(ctx context.Context) error {
	n, err := akdo.akd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apikeys.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (akdo *ApiKeysDeleteOne) ExecX(ctx context.Context) {
	if err := akdo.Exec(ctx); err != nil {
		panic(err)
	}
}
