// Code generated by ent, DO NOT EDIT.

package ent

import (
	"iosync/ent/apikey"
	"iosync/ent/device"
	"iosync/ent/schema"
	"iosync/ent/session"
	"iosync/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescIsActive is the schema descriptor for is_active field.
	apikeyDescIsActive := apikeyFields[3].Descriptor()
	// apikey.DefaultIsActive holds the default value on creation for the is_active field.
	apikey.DefaultIsActive = apikeyDescIsActive.Default.(bool)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[4].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyFields[5].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(time.Time)
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescUsername is the schema descriptor for username field.
	deviceDescUsername := deviceFields[0].Descriptor()
	// device.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	device.UsernameValidator = deviceDescUsername.Validators[0].(func(string) error)
	// deviceDescName is the schema descriptor for name field.
	deviceDescName := deviceFields[1].Descriptor()
	// device.NameValidator is a validator for the "name" field. It is called by the builders before save.
	device.NameValidator = deviceDescName.Validators[0].(func(string) error)
	// deviceDescIsActive is the schema descriptor for is_active field.
	deviceDescIsActive := deviceFields[2].Descriptor()
	// device.DefaultIsActive holds the default value on creation for the is_active field.
	device.DefaultIsActive = deviceDescIsActive.Default.(bool)
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceFields[3].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceFields[4].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescUsername is the schema descriptor for username field.
	sessionDescUsername := sessionFields[1].Descriptor()
	// session.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	session.UsernameValidator = sessionDescUsername.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[2].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[3].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[3].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescLastLogin is the schema descriptor for last_login field.
	userDescLastLogin := userFields[4].Descriptor()
	// user.DefaultLastLogin holds the default value on creation for the last_login field.
	user.DefaultLastLogin = userDescLastLogin.Default.(time.Time)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(time.Time)
}
