// Code generated by ent, DO NOT EDIT.

package ent

import (
	"iosync/ent/apikey"
	"iosync/ent/device"
	"iosync/ent/schema"
	"iosync/ent/session"
	"iosync/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescIsActive is the schema descriptor for is_active field.
	apikeyDescIsActive := apikeyFields[1].Descriptor()
	// apikey.DefaultIsActive holds the default value on creation for the is_active field.
	apikey.DefaultIsActive = apikeyDescIsActive.Default.(bool)
	// apikeyDescLastUsed is the schema descriptor for last_used field.
	apikeyDescLastUsed := apikeyFields[3].Descriptor()
	// apikey.DefaultLastUsed holds the default value on creation for the last_used field.
	apikey.DefaultLastUsed = apikeyDescLastUsed.Default.(func() time.Time)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[4].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyFields[5].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescName is the schema descriptor for name field.
	deviceDescName := deviceFields[0].Descriptor()
	// device.NameValidator is a validator for the "name" field. It is called by the builders before save.
	device.NameValidator = deviceDescName.Validators[0].(func(string) error)
	// deviceDescIsActive is the schema descriptor for is_active field.
	deviceDescIsActive := deviceFields[1].Descriptor()
	// device.DefaultIsActive holds the default value on creation for the is_active field.
	device.DefaultIsActive = deviceDescIsActive.Default.(bool)
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceFields[2].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceFields[3].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[1].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[2].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[3].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescLastLogin is the schema descriptor for last_login field.
	userDescLastLogin := userFields[4].Descriptor()
	// user.DefaultLastLogin holds the default value on creation for the last_login field.
	user.DefaultLastLogin = userDescLastLogin.Default.(func() time.Time)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
