// Code generated by ent, DO NOT EDIT.

package nodevalues

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nodevalues type in the database.
	Label = "node_values"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeNodeAPIKey holds the string denoting the node_api_key edge name in mutations.
	EdgeNodeAPIKey = "node_api_key"
	// Table holds the table name of the nodevalues in the database.
	Table = "node_values"
	// NodeAPIKeyTable is the table that holds the node_api_key relation/edge.
	NodeAPIKeyTable = "node_values"
	// NodeAPIKeyInverseTable is the table name for the NodeApiKey entity.
	// It exists in this package in order to avoid circular dependency with the "nodeapikey" package.
	NodeAPIKeyInverseTable = "node_api_keys"
	// NodeAPIKeyColumn is the table column denoting the node_api_key relation/edge.
	NodeAPIKeyColumn = "node_api_key_values"
)

// Columns holds all SQL columns for nodevalues fields.
var Columns = []string{
	FieldID,
	FieldValue,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "node_values"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"node_api_key_values",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the NodeValues queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNodeAPIKeyField orders the results by node_api_key field.
func ByNodeAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NodeAPIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NodeAPIKeyTable, NodeAPIKeyColumn),
	)
}
